name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    runs-on: macos-latest
    timeout-minutes: 600
    strategy:
      matrix:
        include:
          - os-type: macos
            os-gen: monterey
            os-arch: arm64

          - os-type: macos
            os-gen: monterey
            os-arch: x64

    steps:
      - name: Prepare workspace
        run: rm -rf "${{ github.workspace }}/*"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: "brew install-bundler-gems"

      - run: "brew test-bot --only-cleanup-before"

      - run: "brew test-bot --only-setup"

      - run: "brew test-bot --only-tap-syntax"

      - run: "brew test-bot --only-formulae"
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
